=== mnicolae/XML-Group-Forming/division.dtd
<!ELEMENT Division (Group+)>
<!ATTLIST Division dID ID #REQUIRED>
<!ATTLIST Division maximum CDATA #IMPLIED>
<!ATTLIST Division minimum CDATA #IMPLIED>

<!ELEMENT Group (Student*, Leader, Student*)>
<!ATTLIST Group gID ID #REQUIRED>
<!ELEMENT Leader (#PCDATA)>
<!ELEMENT Student (#PCDATA)>

=== mnicolae/XML-Group-Forming/division.xml
<?xml version="1.0" ?>
<!DOCTYPE Division SYSTEM "division.dtd">
<Division dID="csc301-2011-v1" minimum="1" maximum="4">
	<Group gID="SesameStreet">
		<Student>g0cookie</Student>
		<Student>g0ernie</Student>
		<Leader>g0bigbir</Leader>
	</Group>

	<Group gID="DoratheExplora">
		<Leader>g0dora</Leader>
		<Student>g0diego</Student>
	</Group>

	<Group gID="MaxandRuby">
		<Student>g0max</Student>
		<Leader>g0ruby</Leader>		
	</Group>

	<Group gID="Arthur">
		<Student>g0arthur</Student>
		<Leader>g0dw</Leader>	
		<Student>g0franci</Student>
		<Student>g0brain</Student>
	</Group>
</Division>
