=== mnicolae/XML-Group-Forming/survey.dtd
<!ELEMENT Survey (Title, (MCQuestion|NumQuestion|TimeQuestion)+)>
<!ATTLIST Survey sID ID #REQUIRED>

<!ELEMENT MCQuestion (QText, Options)>
<!ATTLIST MCQuestion qID ID #REQUIRED
		    picks CDATA "1"
		    optionality (mandatory|optional) #REQUIRED>

<!ELEMENT NumQuestion (QText)>
<!ATTLIST NumQuestion qID ID #REQUIRED
		     minValue CDATA #REQUIRED
		     maxValue CDATA #REQUIRED
		     optionality (mandatory|optional) #REQUIRED>

<!ELEMENT TimeQuestion (QText, Options, TimeAnswers)>
<!ATTLIST TimeQuestion qID ID #REQUIRED
		      optionality (mandatory|optional) #REQUIRED>
			
<!ELEMENT Title (#PCDATA)>
<!ELEMENT QText (#PCDATA)>

<!ELEMENT Options (Option, Option, Option*)>
<!ELEMENT Option (#PCDATA)>

<!ELEMENT TimeAnswers (Answer, Answer, Answer?)>
<!ELEMENT Answer (#PCDATA)>

=== mnicolae/XML-Group-Forming/survey.xml
<?xml version="1.0" ?>
<!DOCTYPE Survey SYSTEM "survey.dtd">

<Survey sID="csc301-2011">
  <Title>
    CSC301, fall 2011, group project survey
  </Title>
  <MCQuestion qID="college" optionality="optional">
    <QText>
      What college are you in?
    </QText>
    <Options> 
      <Option>Vic</Option>
      <Option>Innis</Option>
      <Option>UC</Option>
      <Option>Trinity</Option>
      <Option>New</Option>
      <Option>St Mikes</Option>
      <Option>Woodsworth</Option>
    </Options>   
  </MCQuestion>

  <NumQuestion qID="year" minValue="0" maxValue="5" optionality="mandatory">
    <QText>
      What year are you in?
    </QText>
  </NumQuestion>

  <MCQuestion qID="courses" picks="any" optionality="mandatory">
    <QText>
	Which of these courses have you already taken?
    </QText>
    <Options>
      <Option>csc309</Option>
      <Option>csc343</Option>
      <Option>csc318</Option>
      <Option>csc336/350</Option>
    </Options>
  </MCQuestion>
  
  <MCQuestion qID="prefs" picks="2" optionality="mandatory">
    <QText>
      Which of these project domains are most interesting to you? Pick two.
    </QText>
    <Options> 
      <Option>recommender systems</Option>
      <Option>human genome</Option>
      <Option>encryption</Option>
      <Option>gaming</Option>
      <Option>image processing</Option>
      <Option>location-aware apps</Option>
    </Options>
  </MCQuestion>

  <TimeQuestion qID="times" optionality="mandatory">
    <QText>
      When are you available for group meetings?
    </QText>
    <Options>
      <Option>Mondays, 3pm</Option>
      <Option>Mondays, 4pm</Option>
      <Option>Tuesday evenings (after 5pm)</Option>
      <Option>Fridays, 11am</Option>
    </Options>
    <TimeAnswers>
      <Answer>yes</Answer>
      <Answer>no</Answer>
      <Answer>maybe</Answer>
    </TimeAnswers>
  </TimeQuestion>
</Survey>
